services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_general
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - '5433:5432'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db_general
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '81:80'